---
deployment:
  tasks:
    pre_deploy:
      - export DEPLOYPATH=/home2/skybatein/public_html/
      - export DISTPATH=/home2/skybatein/repositories/skybate/dist/portfolio/browser/
    deploy:
      - /bin/bash -c "source /home2/skybatein/nodevenv/repositories/skybate/16/bin/activate && cd /home2/skybatein/repositories/skybate && npm install && npm run build"
      - /bin/cp -R $DISTPATH* $DEPLOYPATH
    post_deploy:
      - echo "Deployment to $DEPLOYPATH completed."
